In [1]:
import numpy as np

# Define the input data and expected output
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Define the sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the sigmoid function
def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Set the learning rate and number of iterations
learning_rate = 0.1
num_iterations = 1000000

# Define the network architecture
input_layer_size = 2
hidden_layer_size = 2
output_layer_size = 1

# Initialize the weights and biases for the hidden and output layers
W1 = np.random.randn(input_layer_size, hidden_layer_size)
b1 = np.random.randn(1, hidden_layer_size)
W2 = np.random.randn(hidden_layer_size, output_layer_size)
b2 = np.random.randn(1, output_layer_size)

# Train the network using backpropagation
for i in range(num_iterations):

    # Forward pass
    hidden_layer_input = np.dot(X, W1) + b1
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, W2) + b2
    output_layer_output = sigmoid(output_layer_input)

    # Calculate the error between the predicted output and the actual output
    error = y - output_layer_output
    
    # Backward pass
    output_layer_error = error * sigmoid_derivative(output_layer_input)
    hidden_layer_error = np.dot(output_layer_error, W2.T) * sigmoid_derivative(hidden_layer_input)
    
    # Update the weights and biases using the calculated errors and the learning rate
    W2 += learning_rate * np.dot(hidden_layer_output.T, output_layer_error)
    b2 += learning_rate * np.sum(output_layer_error, axis=0, keepdims=True)
    W1 += learning_rate * np.dot(X.T, hidden_layer_error)
    b1 += learning_rate * np.sum(hidden_layer_error, axis=0, keepdims=True)

# Print the final output and the predicted output
print(W1)
print(W2)
print("Expected output:\n", y)
print("Predicted output:\n", np.round(output_layer_output))



[[-6.42846053  8.13756577]
 [-6.42194854  8.10361384]]
[[11.75139815]
 [11.59436391]]
Expected output:
 [[0]
 [1]
 [1]
 [0]]
Predicted output:
 [[0.]
 [1.]
 [1.]
 [0.]]
